theme: jekyll-theme-minimal
logo: tux-wein.svg
title: Linux User Group Landau
description: Linux färr die Palz!
lang: de_DE
github:
  is_project_page: false
  is_user_page: false
  show_downloads: false
  
  
